version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket cloudformation-cc-hw3-codepipeline --output-template-file packaged-template.yml
artifacts:
  type: zip
  files:
    - packaged-template.yml